export const texts = [
  "Think of the television",
  "Be frightened of clichés",
  "Do not allow an easement (an easement is the abandonment of a stricture)",
  "What is the fantasy of the situation?",
  "Complex subtraction",
  "Are there sections? Avoid transitions",
  "Put it the right way up",
  "Go quickly around the inside",
  "A line has no sides",
  "Finite gradations",
  "Make an exhaustive list of everything you wouldn't do and do the last thing on the list",
  "Keep instrument roles the same",
  "Out of the impossible",
  "Diminution",
  "Ask people to work with their better judgment",
  "Reconnect with desire",
  "Add elements in order of importance",
  "Hide repetitions",
  "Be afraid of things that are easy to do",
  "Make something missing",
  "Be frightened to display your talents",
  "Use qualified people",
  "Breathe shallowly",
  "How would someone else have done it?",
  "Bismirch thy intent as a hidden error",
  "Ignore differences",
  "More than one element for each kind",
  "Do everything for a short period",
  "Bridges: steal, maintain",
  "Fire",
  "Be ashamed of using your own ideas",
  "Make a calculated constructive predictable action; incorporate",
  "Make it messy",
  "Ignore other sources",
  "The words do not need changing",
  "Use an acceptable colour",
  "Ignore your body",
  "Humanize something full of errors",
  "Do not use filters",
  "Unbalance the consistency principle with the inconsistency principle",
  "Empty every beat with nothing",
  "Embrace an axiomn",
  "Listen to the loud voice",
  "What would you do?",
  "It is finished",
  "Undecorate, undecorate",
  "Remove your earplugs",
  "Take the game back",
  "Forward.",
  "Use normal instruments",
  "Trust in the you of the past",
  "Use more notes",
  "What would a stranger do?",
  "Repitition is not a form of change",
  "Straighten time",
  "Hide your worst impulse",
  "Make a blank worthless by putting it in trash",
  "The consistency principle",
  "Phantom repeats",
  "Break the silence",
  "You can make as many dots as you want",
  "Discover the recipes you are using and adhere to them",
  "Don't carry on",
  "Strain",
  "(Machinised) creatures",
  "Fear!",
  "What mistakes will you make this time?",
  "You are not an engineer",
  "Consider the same fading system",
  "Unmute and stop",
  "Ignore the order in which you do things",
  "It is quite impossible (before all)",
  "Go inside. Open the door.",
  "Stress one thing more than another",
  "We need holes",
  "Dispersion analysis",
  "Work at the same speed",
  "Don't do something boring",
  "Look closely at the least embarrassing details and hide them",
  "Define an area as 'dangerous' and use it as an anchor",
  "Something idiosyncratic, mechanically",
  "Overtly resist stasis",
  "Hide the flaws",
  "Decline advice",
  "Remember those loud evenings",
  "Break a take",
  "The music is now the tape",
  "Long circuit (example: a woman disposing of peas with the idea that they will decrease her virility shovels them straight into her mouth)",
  "Imagine the music as a still chain or centipede",
  "Use a new idea",
  "Aleatory: credibility of, nobility of, humility of",
  "Create: nothing, the most important thing",
  "Imagine the music as a set of connected events",
  "Change everything and continue with immaculate consistency",
  "Imagine the piece as a set of connected events",
  "What are you really thinking about just now? Avoid it.",
  "Adult voices: speaking, singing",
  "Disassemble some of the instruments individually and treat the individuals",
  "Acoustic recordings into a feedback situation",
  "Open the door and listen from inside",
  "Towards the significant",
  "Is the tuning inappropriate",
  "Simply a matter of leisure",
  "Look at a very large object, look away from it's centre",
  "Build a wall but not making a brick",
  "Revaluation (a cold feeling)",
  "Disciplined self-service",
  "The least important thing is the thing most easily remembered",
  "Never first steps",
  "Smart glee",
  "Question the villainous approach",
  "Be minimal",
  "Never give yourself credit for having more than personality",
  "State the problem as vaguely as possible",
  "Faced with a choice, do nothing",
  "Untape your mouth",
  "Untangle the spine",
  "Get your neck destroyed",
  "Lowest common denominator check - every beat - every note - every riff",
  "Ignore the washing up",
  "Listen in complete whiteness, or in a very small room, very loudly",
  "Convert a rhythmic element into a melodic element",
  "Would nobody want it?",
  "Spectrum ignorance",
  "Forget your steps",
  "Go to safety, and move forward to an uncomfortable place",
  "Once the search is in progress, nothing will be found",
  "Only the whole, not one part",
  "From everything to more than everything",
  "Be more critical less often",
];
